### ISSUE TITLE
JDK files link missing and microdnf entitlement certificates

### ISSUE THREAD

**Issue by jralmaraz** [sohrab-/mule4-openshift#1]
Hi Sohrab,

I was reproducing the tutorial (thanks for putting that content together!) and while building the images to deploy Mule on Openshift I realised that the repository link to OpenJDK's tree ends-up missing. I worked-around that by cloning the 'java' repository from fabric8io-images and replaced in the image repo. Thought of raising this issue to note that as well as to ask for a help on the RH subscription-manager related issue (at the end of the image build).

Have you seen this error before ? 

Cheers,

Jose

(process:421): librhsm-WARNING **: 09:40:37.165: Found 0 entitlement certificates
error: (--enablerepo) repo rhel-7-server-rpms not found

======= All detailed logs below:

joalmaraz@myhost:Mulesoft joalmaraz$ git clone https://github.com/sohrab-/mule4-openshift
Cloning into 'mule4-openshift'...
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 61 (delta 18), reused 40 (delta 7), pack-reused 0
Unpacking objects: 100% (61/61), done.
joalmaraz@myhost:Mulesoft joalmaraz$ oc import-image openshift/rhel-minimal:7.6 --from=registry.access.redhat.com/rhel-minimal:7.6 --confirm -n openshift
imagestream.image.openshift.io/rhel-minimal imported

Name:     rhel-minimal
Namespace:    openshift
Created:    4 minutes ago
Labels:     <none>
Annotations:    openshift.io/image.dockerRepositoryCheck=2019-06-14T09:14:40Z
Docker Pull Spec: image-registry.openshift-image-registry.svc:5000/openshift/rhel-minimal
Image Lookup:   local=false
Unique Images:    1
Tags:     1

7.6
  tagged from registry.access.redhat.com/rhel-minimal:7.6

  * registry.access.redhat.com/rhel-minimal@sha256:047376a92086620bcdabc31049bcf2d586809228a544f3a0320ed6a730845c4f
      4 minutes ago

Image Name: rhel-minimal:7.6
Docker Image: registry.access.redhat.com/rhel-minimal@sha256:047376a92086620bcdabc31049bcf2d586809228a544f3a0320ed6a730845c4f
Name:   sha256:047376a92086620bcdabc31049bcf2d586809228a544f3a0320ed6a730845c4f
Created:  2 seconds ago
Annotations:  image.openshift.io/dockerLayersOrder=ascending
Image Size: 32.27MB in 2 layers
Layers:   32.26MB sha256:479fd70922a1968a7cd372cf254dd758f69cd249e97b61df33a9baf552c8b78d
    1.182kB sha256:66ff9d46295ba757d3f3e604920a8df8e8e372549c05e8ee6a7cf0a4a0855423
Image Created:  2 weeks ago
Author:   Red Hat, Inc.
Arch:   amd64
Command:  /bin/bash
Working Dir:  <none>
User:   <none>
Exposes Ports:  <none>
Docker Labels:  architecture=x86_64
    authoritative-source-url=registry.access.redhat.com
    build-date=2019-05-30T15:39:47.794690
    com.redhat.build-host=cpt-0007.osbs.prod.upshift.rdu2.redhat.com
    com.redhat.component=rhel7-atomic-container
    com.redhat.license_terms=https://www.redhat.com/en/about/red-hat-end-user-license-agreements#rhel
    description=The Red Hat Enterprise Linux Base image is designed to be a minimal, fully supported base image where several of the traditional operating system components such as python an systemd have been removed. The Atomic Image also includes a simple package manager called microdnf which can add/update packages as needed.
    distribution-scope=public
    io.k8s.description=The Red Hat Enterprise Linux Base image is designed to be a minimal, fully supported base image where several of the traditional operating system components such as python an systemd have been removed. The Atomic Image also includes a simple package manager called microdnf which can add/update packages as needed.
    io.k8s.display-name=Red Hat Enterprise Linux 7
    io.openshift.tags=minimal rhel7
    name=rhel7-atomic
    release=305
    summary=Provides the latest release of Red Hat Enterprise Linux 7 in a minimal, fully supported base image where several of the traditional operating system components such as python an systemd have been removed.
    url=https://access.redhat.com/containers/#/registry.access.redhat.com/rhel7-atomic/images/7.6-305
    vcs-ref=0acab30b67d90ceb0f078456e79ea2b81792baea
    vcs-type=git
    vendor=Red Hat, Inc.
    version=7.6
Environment:  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    container=oci

joalmaraz@myhost:Mulesoft joalmaraz$ oc apply -f openshift/build.yaml
error: the path "openshift/build.yaml" does not exist
joalmaraz@myhost:Mulesoft joalmaraz$ ls
mule4-openshift
joalmaraz@myhost:Mulesoft joalmaraz$ cd mule4-openshift/
.git/          .gitmodules    LICENSE        README.md      REDHAT_CDK.md  image/         sample-app/    
joalmaraz@myhost:Mulesoft joalmaraz$ cd mule4-openshift/image/
joalmaraz@myhost:image joalmaraz$ oc apply -f openshift/build.yaml
imagestream.image.openshift.io/mule4 unchanged
buildconfig.build.openshift.io/mule4 configured
joalmaraz@myhost:image joalmaraz$ oc start-build buildConfig/mule4 --from-dir=. --wait --follow
Uploading directory "." as binary input for the build ...
..
Uploading finished
build.build.openshift.io/mule4-2 started
Receiving source from STDIN as archive ...
Replaced Dockerfile FROM image registry.access.redhat.com/rhel-minimal:7.6
Caching blobs under "/var/cache/blobs".

Pulling image registry.access.redhat.com/rhel-minimal@sha256:047376a92086620bcdabc31049bcf2d586809228a544f3a0320ed6a730845c4f ...
Getting image source signatures
Copying blob sha256:66ff9d46295ba757d3f3e604920a8df8e8e372549c05e8ee6a7cf0a4a0855423
Copying blob sha256:479fd70922a1968a7cd372cf254dd758f69cd249e97b61df33a9baf552c8b78d
Copying config sha256:4364d4c393fff2812bc91d2776c5a553ee5a384f14316bf84ed7f0811eb1e0d8
Writing manifest to image destination
Storing signatures
STEP 1: FROM registry.access.redhat.com/rhel-minimal@sha256:047376a92086620bcdabc31049bcf2d586809228a544f3a0320ed6a730845c4f
STEP 2: ARG JAVA_VERSION=1.8.0
--> 4e38322d5be4815859fe50a2498f537e405107133c6e18efc06786c530222248
STEP 3: ARG MULE_VERSION=4.1.5
--> f1253173d5037f4709f0b0f891c08bf13eb7e0a515e910e83441b29bdaa64924
STEP 4: ARG AGENT_BOND_VERSION=1.2.0
--> eccba1aafe88f134061974fc4904ea99d0ac1f01f764eca00275b69adf93debd
STEP 5: ENV JAVA_MAJOR_VERSION=8 JAVA_HOME=/usr/lib/jvm/jre MULE_HOME=/opt/mule DEPLOYMENTS_DIR=/deployments S2I_SCRIPTS_DIR=/usr/local/s2i JAVA_APP_NAME=mule JAVA_APP_DIR=${MULE_HOME} JAVA_LIB_DIR=/opt JAVA_MAIN_CLASS=org.mule.runtime.module.launcher.MuleContainer
--> e406439926dc11bfcf439b065af73cce223d7904087214b668550d68e8113d02
STEP 6: LABEL maintainer="sohrab" name="mule4" summary="Mule:Unwrapped 4 on mininmal RHEL" description="Source To Image (S2I) Mule:Unwrapped image for Red Hat OpenShift" io.k8s.display-name="Mule:Unwrapped 4" io.k8s.description="Source To Image (S2I) Mule:Unwrapped image for Red Hat OpenShift" io.openshift.s2i.destination="${DEPLOYMENTS_DIR}" io.openshift.s2i.scripts-url="image://${S2I_SCRIPTS_DIR}" io.openshift.tags="mule,java"
--> c6fea41212146d8a5c57b02d4269cf27289699c40282a43380f99af9df9a18fa
STEP 7: EXPOSE 8778 9779
--> 13d00f0355528407d2b0bb09d1430e1d43788e54f0d5c3f1d99135842ce42a64
STEP 8: CMD ["/deployments/run-java.sh"]
--> 34eaa161debd968ce157db0b1952bd2cf279016549c3ba4f14d287a010cfe1d3
STEP 9: USER root
--> f00cb89f47576467a80f84b29e170ecd75f97482d2d359e4a42204dab5e58416
STEP 10: COPY fabric8-java-images/images/jboss/openjdk8/jdk/agent-bond-opts /opt/agent-**bond-opts
error: build error: error building at STEP "COPY fabric8-java-images/images/jboss/openjdk8/jdk/agent-bond-opts /opt/agent-bond-opts": no files found matching "/tmp/build/inputs/fabric8-java-images/images/jboss/openjdk8/jdk/agent-bond-opts": no such file or directory
error: the build default/mule4-2 status is "Failed"**

joalmaraz@myhost:image joalmaraz$ ls
Dockerfile    README.md   assemble    classpath   fabric8-java-images openshift   run     run-java-options

joalmaraz@myhost:image joalmaraz$ git clone https://github.com/fabric8io-images/java/
Cloning into 'java'...
remote: Enumerating objects: 214, done.
remote: Counting objects: 100% (214/214), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 1483 (delta 98), reused 199 (delta 92), pack-reused 1269
Receiving objects: 100% (1483/1483), 186.21 KiB | 333.00 KiB/s, done.
Resolving deltas: 100% (873/873), done.
joalmaraz@myhost:image joalmaraz$ rm -rf fabric8-java-images
joalmaraz@myhost:image joalmaraz$ mv java/ fabric8-java-images
joalmaraz@myhost:image joalmaraz$ ls -la fabric8-java-images/
total 56
drwxr-xr-x  11 joalmaraz  2064491805    352 14 Jun 19:21 .
drwxr-xr-x  12 joalmaraz  2064491805    384 14 Jun 19:21 ..
drwxr-xr-x  12 joalmaraz  2064491805    384 14 Jun 19:21 .git
-rw-r--r--   1 joalmaraz  2064491805     35 14 Jun 19:21 .gitignore
-rw-r--r--   1 joalmaraz  2064491805  11347 14 Jun 19:21 LICENSE
-rw-r--r--   1 joalmaraz  2064491805   1631 14 Jun 19:21 README.md
drwxr-xr-x   4 joalmaraz  2064491805    128 14 Jun 19:21 blocks
-rw-r--r--   1 joalmaraz  2064491805    554 14 Jun 19:21 fish-pepper.yml
drwxr-xr-x   5 joalmaraz  2064491805    160 14 Jun 19:21 images
-rw-r--r--   1 joalmaraz  2064491805   1592 14 Jun 19:21 images.yml
drwxr-xr-x   5 joalmaraz  2064491805    160 14 Jun 19:21 templates
joalmaraz@myhost:image joalmaraz$ ls fabric8-java-images/images/jboss/openjdk
openjdk7/ openjdk8/ 
joalmaraz@myhost:image joalmaraz$ ls fabric8-java-images/images/jboss/openjdk8/jdk/
Dockerfile               README.md                agent-bond-opts          jmx_exporter_config.yml  run-java.sh              
joalmaraz@myhost:image joalmaraz$ ls fabric8-java-images/images/jboss/openjdk8/jdk/
Dockerfile               README.md                agent-bond-opts          jmx_exporter_config.yml  run-java.sh              
joalmaraz@myhost:image joalmaraz$ ls fabric8-java-images/images/jboss/openjdk8/jdk/
joalmaraz@myhost:image joalmaraz$ 
joalmaraz@myhost:image joalmaraz$ 
joalmaraz@myhost:image joalmaraz$ ls
Dockerfile    README.md   assemble    classpath   fabric8-java-images openshift   run     run-java-options

----- After JDK location fix

joalmaraz@myhost:image joalmaraz$ oc start-build buildConfig/mule4 --from-dir=. --wait --follow
Uploading directory "." as binary input for the build ...
.........
Uploading finished
build.build.openshift.io/mule4-5 started
Receiving source from STDIN as archive ...
Replaced Dockerfile FROM image registry.access.redhat.com/rhel-minimal:7.6
Caching blobs under "/var/cache/blobs".

Pulling image registry.access.redhat.com/rhel-minimal@sha256:047376a92086620bcdabc31049bcf2d586809228a544f3a0320ed6a730845c4f ...
Getting image source signatures
Copying blob sha256:479fd70922a1968a7cd372cf254dd758f69cd249e97b61df33a9baf552c8b78d
Copying blob sha256:66ff9d46295ba757d3f3e604920a8df8e8e372549c05e8ee6a7cf0a4a0855423
Copying config sha256:4364d4c393fff2812bc91d2776c5a553ee5a384f14316bf84ed7f0811eb1e0d8
Writing manifest to image destination
Storing signatures
STEP 1: FROM registry.access.redhat.com/rhel-minimal@sha256:047376a92086620bcdabc31049bcf2d586809228a544f3a0320ed6a730845c4f
STEP 2: ARG JAVA_VERSION=1.8.0
--> 3fe66e50d1f83a5ec4a9c7792d084ce4cdc8048178e7e79295fb65efaf1e51e9
STEP 3: ARG MULE_VERSION=4.2.0
--> ce98d7ccce6146f0a1e255231b4858333492fe625ad0bb0818bd18d121135ff8
STEP 4: ARG AGENT_BOND_VERSION=1.2.0
--> 3360556a53a9cfe54b3d4e0060c2849b06c2e7a1fa16cc9feca5ee30b6a75a6b
STEP 5: ENV JAVA_MAJOR_VERSION=8 JAVA_HOME=/usr/lib/jvm/jre MULE_HOME=/opt/mule DEPLOYMENTS_DIR=/deployments S2I_SCRIPTS_DIR=/usr/local/s2i JAVA_APP_NAME=mule JAVA_APP_DIR=${MULE_HOME} JAVA_LIB_DIR=/opt JAVA_MAIN_CLASS=org.mule.runtime.module.launcher.MuleContainer
--> 0a3ae5fb12ffef58c9ef89e3c824b6bb8d46dee706019415d0be5429b286bfeb
STEP 6: LABEL maintainer="sohrab" name="mule4" summary="Mule:Unwrapped 4 on mininmal RHEL" description="Source To Image (S2I) Mule:Unwrapped image for Red Hat OpenShift" io.k8s.display-name="Mule:Unwrapped 4" io.k8s.description="Source To Image (S2I) Mule:Unwrapped image for Red Hat OpenShift" io.openshift.s2i.destination="${DEPLOYMENTS_DIR}" io.openshift.s2i.scripts-url="image://${S2I_SCRIPTS_DIR}" io.openshift.tags="mule,java"
--> 64eecb4f8dc19fd368420052692f6c0234bbe125911a60ad006cd7d369a2c6fe
STEP 7: EXPOSE 8778 9779
--> 252100538a1e8e8df36b954b479f82fa534712971ff94460fafd73cfe7d55527
STEP 8: CMD ["/deployments/run-java.sh"]
--> 6a4c09f0dee3ad4f31a8c6e40f67831dcae8ca0713798403ccbc52f6493447c5
STEP 9: USER root
--> 115cdfd79197cd136833b95aaacb9bc83ecbac4e1b69e3900d0837620de9d05a
STEP 10: COPY fabric8-java-images/images/jboss/openjdk8/jdk/agent-bond-opts /opt/agent-bond-opts
--> a9c935fab15950ceb19fc4670db76cfdd3e3ac061e02f21dbb9bb7f006d6f31f
STEP 11: COPY fabric8-java-images/images/jboss/openjdk8/jdk/jmx_exporter_config.yml /opt/agent-bond/
--> abc511c9b220fb3160dec99802f80b4f6a9da08ea52e837522ee7386c4777b19
STEP 12: COPY fabric8-java-images/images/jboss/openjdk8/jdk/run-java.sh ${DEPLOYMENTS_DIR}/
--> 810c376fb8c699292e05d8883a528adadc43e1b426884c5e670b09f0960e8d2f
STEP 13: COPY run-java-options classpath /opt/
--> 2a5aadee22d0895cef95f7cd2121926bb5526769bf684876df67bcc9bc1bef68
STEP 14: COPY assemble run /usr/local/s2i/
--> 9f8a05789b48d0dff045ee59eb7a12bcb7a0f2b092f20dbd5b4bf1a7d89fc673
STEP 15: COPY mule-ee-distribution-standalone-${MULE_VERSION}.tar.gz /tmp/
--> 33d07108b0f1004837a6c79425cee68a43772222a921f42285adf9c46e65b3ac
STEP 16: RUN microdnf --enablerepo=rhel-7-server-rpms --nodocs install     gzip     java-${JAVA_VERSION}-openjdk-headless     tar     unzip   && tar -xvf /tmp/mule-ee-distribution-standalone-${MULE_VERSION}.tar.gz --directory /opt 	&& ln -s /opt/mule-enterprise-standalone-${MULE_VERSION} ${MULE_HOME}   && curl --fail --silent --show-error     http://central.maven.org/maven2/io/fabric8/agent-bond-agent/${AGENT_BOND_VERSION}/agent-bond-agent-${AGENT_BOND_VERSION}.jar     > /opt/agent-bond/agent-bond.jar   && chown -R 1001:root /opt ${S2I_SCRIPTS_DIR} ${DEPLOYMENTS_DIR}   && chmod -R g+rwX /opt ${S2I_SCRIPTS_DIR} ${DEPLOYMENTS_DIR}   && chmod +x ${DEPLOYMENTS_DIR}/run-java.sh ${S2I_SCRIPTS_DIR}/{assemble,run}   && rm -rvf /tmp/mule-ee-distribution-standalone-${MULE_VERSION}.tar.gz   **&& microdnf clean all

(process:421): librhsm-WARNING **: 09:40:37.163: Found 0 entitlement certificates

(process:421): librhsm-WARNING **: 09:40:37.165: Found 0 entitlement certificates
error: (--enablerepo) repo rhel-7-server-rpms not found
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN microdnf --enablerepo=rhel-7-server-rpms --nodocs install     gzip     java-${JAVA_VERSION}-openjdk-headless     tar     unzip   && tar -xvf /tmp/mule-ee-distribution-standalone-${MULE_VERSION}.tar.gz --directory /opt 	&& ln -s /opt/mule-enterprise-standalone-${MULE_VERSION} ${MULE_HOME}   && curl --fail --silent --show-error     http://central.maven.org/maven2/io/fabric8/agent-bond-agent/${AGENT_BOND_VERSION}/agent-bond-agent-${AGENT_BOND_VERSION}.jar     > /opt/agent-bond/agent-bond.jar   && chown -R 1001:root /opt ${S2I_SCRIPTS_DIR} ${DEPLOYMENTS_DIR}   && chmod -R g+rwX /opt ${S2I_SCRIPTS_DIR} ${DEPLOYMENTS_DIR}   && chmod +x ${DEPLOYMENTS_DIR}/run-java.sh ${S2I_SCRIPTS_DIR}/{assemble,run}   && rm -rvf /tmp/mule-ee-distribution-standalone-${MULE_VERSION}.tar.gz   && microdnf clean all": exit status 1
error: the build default/mule4-5 status is "Failed"**

**Comment by sohrab-** [comment]
Hey @jralmaraz, a couple of things:

* OpenJDK stuff is a git submodule. You need to probably do a `git submodule update --init --recursive` on the first clone for it to bring that in and `git submodule update --recursive` on subsequent updates.
* Re the error, are you running [Red Hat CDK](https://developers.redhat.com/products/cdk) per documentation? CDK gives you a free developer license to do yum installs in the RHEL images. It looks like your current instance does not have that entitlement. 

Btw Red Hat recently announced UBIs which no longer require a licence so once I get a chance I move this image to that base.

**Comment by jralmaraz** [comment]
Hi @sohrab- ,

Thanks for the update on the JDK, I knew I was missing something, but couldn't tell.

In regards to the deployment, I ran the new installer of openshift 4 against an AWS environment, so I wasn't using CDK. 

I have updated the Dockerfile to use the indicated UBI, but need some more tweaks to make it all work with the new mule image as well, as, even though the image build was completed, there were plenty of "unknown extended header" messages, so I couldn't fully test it yet.

Thanks again for the attention.

Cheers.

**Comment by jralmaraz** [comment]
docker build -t mule4 .
Sending build context to Docker daemon    298MB
Step 1/17 : FROM registry.access.redhat.com/ubi7/ubi-minimal
 ---> 6969a765dae2
Step 2/17 : ARG JAVA_VERSION=1.8.0
 ---> Using cache
 ---> 8358a8e54ae2
Step 3/17 : ARG MULE_VERSION=4.2.0
 ---> Using cache
 ---> ad9d344bba55
Step 4/17 : ARG AGENT_BOND_VERSION=1.2.0
 ---> Using cache
 ---> 0e45b6097bd3
Step 5/17 : ENV   JAVA_MAJOR_VERSION=8   JAVA_HOME=/usr/lib/jvm/jre   MULE_HOME=/opt/mule   DEPLOYMENTS_DIR=/deployments   S2I_SCRIPTS_DIR=/usr/local/s2i   JAVA_APP_NAME=mule   JAVA_APP_DIR=${MULE_HOME}   JAVA_LIB_DIR=/opt   JAVA_MAIN_CLASS=org.mule.runtime.module.launcher.MuleContainer
 ---> Using cache
 ---> 9e5875621a98
Step 6/17 : LABEL   maintainer="sohrab"   name="mule4"   summary="Mule:Unwrapped 4 on mininmal RHEL"   description="Source To Image (S2I) Mule:Unwrapped image for Red Hat OpenShift"   io.k8s.display-name="Mule:Unwrapped 4"   io.k8s.description="Source To Image (S2I) Mule:Unwrapped image for Red Hat OpenShift"   io.openshift.s2i.destination="${DEPLOYMENTS_DIR}"   io.openshift.s2i.scripts-url="image://${S2I_SCRIPTS_DIR}"   io.openshift.tags="mule,java"
 ---> Using cache
 ---> af03b1064f6e
Step 7/17 : EXPOSE 8778 9779
 ---> Using cache
 ---> 8e4e166fb08a
Step 8/17 : CMD [ "/deployments/run-java.sh" ]
 ---> Using cache
 ---> eddc14da26a8
Step 9/17 : USER root
 ---> Using cache
 ---> 898957229e6e
Step 10/17 : COPY fabric8-java-images/images/jboss/openjdk8/jdk/agent-bond-opts /opt/agent-bond-opts
 ---> Using cache
 ---> 295063a1be94
Step 11/17 : COPY fabric8-java-images/images/jboss/openjdk8/jdk/jmx_exporter_config.yml /opt/agent-bond/
 ---> Using cache
 ---> 896813ec6247
Step 12/17 : COPY fabric8-java-images/images/jboss/openjdk8/jdk/run-java.sh ${DEPLOYMENTS_DIR}/
 ---> Using cache
 ---> 6b9dbda54d13
Step 13/17 : COPY run-java-options classpath /opt/
 ---> Using cache
 ---> e6b620136ce5
Step 14/17 : COPY assemble run /usr/local/s2i/
 ---> Using cache
 ---> 36b07714599c
Step 15/17 : COPY mule-ee-distribution-standalone-${MULE_VERSION}.tar.gz /tmp/
 ---> Using cache
 ---> 37c8caec3428
Step 16/17 : RUN   microdnf --nodocs install     gzip     java-${JAVA_VERSION}-openjdk-headless     tar     unzip   && tar -xvf /tmp/mule-ee-distribution-standalone-${MULE_VERSION}.tar.gz --directory /opt 	&& ln -s /opt/mule-enterprise-standalone-${MULE_VERSION} ${MULE_HOME}   && curl --fail --silent --show-error     http://central.maven.org/maven2/io/fabric8/agent-bond-agent/${AGENT_BOND_VERSION}/agent-bond-agent-${AGENT_BOND_VERSION}.jar     > /opt/agent-bond/agent-bond.jar   && chown -R 1001:root /opt ${S2I_SCRIPTS_DIR} ${DEPLOYMENTS_DIR}   && chmod -R g+rwX /opt ${S2I_SCRIPTS_DIR} ${DEPLOYMENTS_DIR}   && chmod +x ${DEPLOYMENTS_DIR}/run-java.sh ${S2I_SCRIPTS_DIR}/{assemble,run}   && rm -rvf /tmp/mule-ee-distribution-standalone-${MULE_VERSION}.tar.gz   && microdnf clean all
 ---> Running in 6ab0135e28c8

(process:7): librhsm-WARNING **: 06:22:44.881: Found 0 entitlement certificates

(process:7): librhsm-WARNING **: 06:22:44.886: Found 0 entitlement certificates
Downloading metadata...
Downloading metadata...
Downloading metadata...
Downloading metadata...
Transaction: 51 packages
binutils-2.27-34.base.el7.x86_64 (ubi-7)
dracut-033-554.el7.x86_64 (ubi-7)
device-mapper-7:1.02.149-10.el7_6.8.x86_64 (ubi-7)
libutempter-1.1.6-4.el7.x86_64 (ubi-7)
hardlink-1:1.0-19.el7.x86_64 (ubi-7)
util-linux-2.23.2-59.el7_6.1.x86_64 (ubi-7)
python-libs-2.7.5-79.el7_6.x86_64 (ubi-7)
kmod-20-23.el7.x86_64 (ubi-7)
dbus-libs-1:1.10.24-13.el7_6.x86_64 (ubi-7)
javapackages-tools-3.4.1-11.el7.noarch (ubi-7)
tar-2:1.26-35.el7.x86_64 (ubi-7)
ustr-1.0.4-16.el7.x86_64 (ubi-7)
gdbm-1.10-8.el7.x86_64 (ubi-7)
libxslt-1.1.28-5.el7.x86_64 (ubi-7)
libpng-2:1.5.13-7.el7_2.x86_64 (ubi-7)
unzip-6.0-19.el7.x86_64 (ubi-7)
libjpeg-turbo-1.2.90-6.el7.x86_64 (ubi-7)
kpartx-0.4.9-123.el7.x86_64 (ubi-7)
tzdata-java-2019a-1.el7.noarch (ubi-7)
lksctp-tools-1.0.17-2.el7.x86_64 (ubi-7)
elfutils-libs-0.172-2.el7.x86_64 (ubi-7)
systemd-libs-219-62.el7_6.7.x86_64 (ubi-7)
acl-2.2.51-14.el7.x86_64 (ubi-7)
python-javapackages-3.4.1-11.el7.noarch (ubi-7)
elfutils-default-yama-scope-0.172-2.el7.noarch (ubi-7)
cpio-2.11-27.el7.x86_64 (ubi-7)
libsemanage-2.5-14.el7.x86_64 (ubi-7)
procps-ng-3.3.10-23.el7.x86_64 (ubi-7)
pam-1.1.8-22.el7.x86_64 (ubi-7)
systemd-219-62.el7_6.7.x86_64 (ubi-7)
shadow-utils-2:4.1.5.1-25.el7_6.1.x86_64 (ubi-7)
pcsc-lite-libs-1.8.8-8.el7.x86_64 (ubi-7)
python-2.7.5-79.el7_6.x86_64 (ubi-7)
qrencode-libs-3.4.1-3.el7.x86_64 (ubi-7)
gzip-1.5-10.el7.x86_64 (ubi-7)
copy-jdk-configs-3.3-10.el7_5.noarch (ubi-7)
java-1.8.0-openjdk-headless-1:1.8.0.212.b04-0.el7_6.x86_64 (ubi-7)
avahi-libs-0.6.31-19.el7.x86_64 (ubi-7)
libpwquality-1.2.3-5.el7.x86_64 (ubi-7)
device-mapper-libs-7:1.02.149-10.el7_6.8.x86_64 (ubi-7)
freetype-2.8-12.el7_6.1.x86_64 (ubi-7)
cracklib-dicts-2.9.0-11.el7.x86_64 (ubi-7)
python-lxml-3.2.1-4.el7.x86_64 (ubi-7)
libuser-0.60-9.el7.x86_64 (ubi-7)
cups-libs-1:1.6.3-35.el7.x86_64 (ubi-7)
cryptsetup-libs-2.0.3-3.el7.x86_64 (ubi-7)
diffutils-3.3-4.el7.x86_64 (ubi-7)
cracklib-2.9.0-11.el7.x86_64 (ubi-7)
kmod-libs-20-23.el7.x86_64 (ubi-7)
dbus-1:1.10.24-13.el7_6.x86_64 (ubi-7)
xz-5.2.2-1.el7.x86_64 (ubi-7)
Downloading packages...
Running transaction test...
Installing: gzip;1.5-10.el7;x86_64;ubi-7
Installing: cracklib;2.9.0-11.el7;x86_64;ubi-7
Installing: cracklib-dicts;2.9.0-11.el7;x86_64;ubi-7
Installing: libpwquality;1.2.3-5.el7;x86_64;ubi-7
Installing: pam;1.1.8-22.el7;x86_64;ubi-7
Installing: xz;5.2.2-1.el7;x86_64;ubi-7
Installing: diffutils;3.3-4.el7;x86_64;ubi-7
Installing: (null)
install-info: No such file or directory for /usr/share/info/diffutils.info
Installing: cpio;2.11-27.el7;x86_64;ubi-7
Installing: libxslt;1.1.28-5.el7;x86_64;ubi-7
Installing: (null)
Installing: libuser;0.60-9.el7;x86_64;ubi-7
Installing: (null)
Installing: kmod-libs;20-23.el7;x86_64;ubi-7
Installing: (null)
Installing: copy-jdk-configs;3.3-10.el7_5;noarch;ubi-7
Installing: (null)
Installing: qrencode-libs;3.4.1-3.el7;x86_64;ubi-7
Installing: (null)
Installing: pcsc-lite-libs;1.8.8-8.el7;x86_64;ubi-7
Installing: acl;2.2.51-14.el7;x86_64;ubi-7
Installing: (null)
Installing: lksctp-tools;1.0.17-2.el7;x86_64;ubi-7
Installing: (null)
Installing: tzdata-java;2019a-1.el7;noarch;ubi-7
Installing: (null)
Installing: libjpeg-turbo;1.2.90-6.el7;x86_64;ubi-7
Installing: (null)
Installing: libpng;2:1.5.13-7.el7_2;x86_64;ubi-7
Installing: (null)
Installing: freetype;2.8-12.el7_6.1;x86_64;ubi-7
Installing: (null)
Installing: gdbm;1.10-8.el7;x86_64;ubi-7
Installing: python-libs;2.7.5-79.el7_6;x86_64;ubi-7
Installing: python;2.7.5-79.el7_6;x86_64;ubi-7
Installing: (null)
Installing: python-lxml;3.2.1-4.el7;x86_64;ubi-7
Installing: python-javapackages;3.4.1-11.el7;noarch;ubi-7
Installing: (null)
Installing: javapackages-tools;3.4.1-11.el7;noarch;ubi-7
Installing: (null)
Installing: ustr;1.0.4-16.el7;x86_64;ubi-7
Installing: (null)
Installing: libsemanage;2.5-14.el7;x86_64;ubi-7
Installing: (null)
Installing: shadow-utils;2:4.1.5.1-25.el7_6.1;x86_64;ubi-7
Installing: (null)
Installing: libutempter;1.1.6-4.el7;x86_64;ubi-7
Installing: (null)
Installing: tar;2:1.26-35.el7;x86_64;ubi-7
Installing: (null)
Installing: hardlink;1:1.0-19.el7;x86_64;ubi-7
Installing: (null)
Installing: binutils;2.27-34.base.el7;x86_64;ubi-7
Installing: (null)
install-info: No such file or directory for /usr/share/info/as.info.gz
install-info: No such file or directory for /usr/share/info/binutils.info.gz
install-info: No such file or directory for /usr/share/info/gprof.info.gz
install-info: No such file or directory for /usr/share/info/ld.info.gz
install-info: No such file or directory for /usr/share/info/standards.info.gz
Installing: util-linux;2.23.2-59.el7_6.1;x86_64;ubi-7
Installing: (null)
Installing: procps-ng;3.3.10-23.el7;x86_64;ubi-7
Installing: device-mapper;7:1.02.149-10.el7_6.8;x86_64;ubi-7
Installing: (null)
Installing: kpartx;0.4.9-123.el7;x86_64;ubi-7
Installing: (null)
Installing: dracut;033-554.el7;x86_64;ubi-7
Installing: (null)
Installing: kmod;20-23.el7;x86_64;ubi-7
Installing: (null)
Installing: device-mapper-libs;7:1.02.149-10.el7_6.8;x86_64;ubi-7
Installing: (null)
Installing: cryptsetup-libs;2.0.3-3.el7;x86_64;ubi-7
Installing: (null)
Installing: elfutils-libs;0.172-2.el7;x86_64;ubi-7
Installing: (null)
Installing: systemd-libs;219-62.el7_6.7;x86_64;ubi-7
Installing: (null)
Installing: dbus-libs;1:1.10.24-13.el7_6;x86_64;ubi-7
Installing: systemd;219-62.el7_6.7;x86_64;ubi-7
Installing: (null)
Failed to get D-Bus connection: Operation not permitted
Installing: elfutils-default-yama-scope;0.172-2.el7;noarch;ubi-7
Installing: (null)
Installing: dbus;1:1.10.24-13.el7_6;x86_64;ubi-7
Installing: (null)
Installing: avahi-libs;0.6.31-19.el7;x86_64;ubi-7
Installing: (null)
Installing: cups-libs;1:1.6.3-35.el7;x86_64;ubi-7
Installing: (null)
Installing: java-1.8.0-openjdk-headless;1:1.8.0.212.b04-0.el7_6;x86_64;ubi-7
Installing: (null)
Installing: unzip;6.0-19.el7;x86_64;ubi-7
Installing: (null)
Complete.
tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
./._mule-enterprise-standalone-4.2.0
tar: Ignoring unknown extended header keyword `SCHILY.dev'
......CUT
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
removed '/tmp/mule-ee-distribution-standalone-4.2.0.tar.gz'

(process:180): librhsm-WARNING **: 06:24:40.523: Found 0 entitlement certificates

(process:180): librhsm-WARNING **: 06:24:40.527: Found 0 entitlement certificates
Complete.
Removing intermediate container 6ab0135e28c8
 ---> 60e108713bf3
Step 17/17 : USER 1001
 ---> Running in 5975077d6e44
Removing intermediate container 5975077d6e44
 ---> 806af99ea23c
Successfully built 806af99ea23c
Successfully tagged mule4:latest
