### ISSUE TITLE
An Unwrapped Mule 4.2.x?

### ISSUE THREAD

**Issue by devnotfound** [sohrab-/mule4-openshift#2]
Hey Sohrab-,
Believe you said in your blog that the 4.2.x runtime breaks this approach.
Are you still keen on using the org.mule.runtime.module.reboot.MuleContainerBootstrap class and running the container with a process signature almost identical to the stock MuleSoft approach?
Accepting PR's?

Cheers

**Comment by sohrab-** [comment]
Thanks for the PR!
